describe('Test beers page', () => {
  it('goes to beers page', () => {
    cy.visit('/beers')
    cy.get('[data-cy="grid-beer-1"]')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Name: Buzz')
  })

  it('goes to beers page 2 by clicking on 2', () => {
    cy.get('[data-cy="pagination"] > .MuiPagination-ul')
      .children()
      .eq(2)
      .contains('2')
      .click()
    cy.get('[data-cy="grid-beer-11"]')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Name: Misspent Youth')
  })

  it('goes to beers page 3 by clicking next button', () => {
    cy.get('[data-cy="pagination"] > .MuiPagination-ul')
      .children()
      .eq(8)
      .children()
      .get('[data-testid="NavigateNextIcon"]')
      .click()
    cy.get('[data-cy="grid-beer-21"]')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Name: Vice Bier')
  })

  it('goes to beers page 2 by clicking back button', () => {
    cy.get('[data-cy="pagination"] > .MuiPagination-ul')
      .children()
      .get('[data-testid="NavigateBeforeIcon"]')
      .click()
    cy.get('[data-cy="grid-beer-11"]')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Name: Misspent Youth')
  })

  it('opens beers table view', () => {
    cy.visit('/beers')
    cy.get('[data-cy="table-view-button"]')
      .should('exist')
      .and('be.visible')
      .click()
    cy.get('[data-cy="table-view"]')
      .should('exist')
      .and('be.visible')
      .children()
    cy.get('[data-id="1"] > [data-field="name"] > .MuiDataGrid-cellContent')
      .should('contain', 'Buzz')
    cy.get('[data-cy="beer-grid"]')
      .should('not.exist')
  })

  it('uses search bar', () => {
    cy.get('[data-cy="search-input"]')
      .children()
      .type('buzz')
      .should('have.value', 'buzz')
    cy.get('[data-cy="search-button"]')
      .click()
    cy.get('[data-id="1"] > [data-field="id"]')
      .should('exist')
      .and('be.visible')
    cy.get('[data-id="1"] > [data-field="name"] > .MuiDataGrid-cellContent')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Buzz')
    cy.get('[data-id="2"] > [data-field="id"]')
      .should('not.exist')
    cy.get('[data-cy="search-input"]')
      .children()
      .type('{selectall}{backspace}')
    cy.get('[data-cy="pagination"]')
      .should('exist')
      .and('be.visible')
    cy.get('[data-id="2"] > [data-field="id"]')
      .should('exist')
      .and('be.visible')
  })
})