describe('Visit my account page', () => {
  it('goes to my account page', () => {
    cy.visit('/pokemons')
    cy.get('[data-cy="My Account"]')
      .click()
    cy.url()
      .should('include', '/myAccount')
    cy.get('[data-cy="gender"]')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Gender:')
    cy.get('[data-cy="phone"]')
      .should('exist')
      .and('be.visible')
      .and('contain', 'Phone:')
    cy.get('[data-cy="user"]')
      .should('not.be.empty')
  })
})